### ISSUE TITLE
Module arrow

### ISSUE THREAD

**Issue by matteoFeduzi** [nickpettican/InstaBot#24]
Error:

Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from src.instabot import InstaBot
  File "/Users/FeduziMatteo/Desktop/InstaBot-master/src/instabot.py", line 23, in <module>
    import arrow
ImportError: No module named arrow

**Comment by nickpettican** [comment]
Hi @matteoFeduzi thanks for the feedback.
You can solve this by running `pip install arrow` or `sudo pip install arrow`

**Comment by DoniSatria** [comment]
python2 run.py
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from src.instabot import InstaBot
ImportError: No module named src.instabot
$

**Comment by nickpettican** [comment]
Try `python run.py`, make sure you're using python 2.7. 
You can check by running `python` by itself and seeing if you get Python 2.7.* in your output.
