### ISSUE TITLE
Error while commenting - debugging needed:

### ISSUE THREAD

**Issue by Andreatop90** [nickpettican/InstaBot#51]
[ 2018-12-11 18:12:08 ]  * Trying to comment "https://www.instagram.com/p/BrQZuAkg56r/":  Error:
while commenting - debugging needed:
in explore operation - debugging needed:
Traceback (most recent call last):
  File "/home/ubuntu/InstaBot-master/src/instabot.py", line 735, in main
    self.main_loop()
  File "/home/ubuntu/InstaBot-master/src/instabot.py", line 802, in main_loop
    response = self.insta_operation(operation)
  File "/home/ubuntu/InstaBot-master/src/instabot.py", line 926, in insta_operation
    return self.comment_media(False)
  File "/home/ubuntu/InstaBot-master/src/instabot.py", line 1029, in comment_media
    raise Exception('\nwhile commenting - debugging needed: %s' % (e))
Exception:
while commenting - debugging needed:
in explore operation - debugging needed:

**Comment by nickpettican** [comment]
Hi @Andreatop90  thanks for the feedback. And thanks for finding the bug. Could you update InstaBot to the latest version and provide the full logs? I don't know what the exact error is.

**Comment by nickpettican** [comment]
Closing this as it's gone cold
