### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by followsmoke** [nickpettican/InstaBot#65]
Hi all,
It's been a while since there has been no answer here, but I'm still trying!

I have an import problem.

Traceback (most recent call last):
  File "/Users/adrien/Downloads/InstaBot-master_nick/run.py", line 23, in <module>
    from src.instabot import InstaBot
  File "/Users/adrien/Downloads/InstaBot-master_nick/src/instabot.py", line 35, in <module>
    from src.miscellaneous import *
  File "/Users/adrien/Downloads/InstaBot-master_nick/src/miscellaneous.py", line 24, in <module>
    import numpy as np
ImportError: No module named numpy
logout

Do you have a solution?

Thanks a lot

**Comment by slim-python** [comment]
Hey, I guess he hasn't added the latest version of NumPy in requirements.txt, try running `pip install numpy` in your command prompt and then see if it works.
