### ISSUE TITLE
Apologies, I could not sign you in.

### ISSUE THREAD

**Issue by fmchan** [nickpettican/InstaBot#67]
[ 2020-09-12 21:09:43 ] Trying to sign in as USERNAME:
ERROR signing in, InstaBot probably failed to obtain Instagram's cookies
Traceback (most recent call last):
  File "/Users/XXX/Documents/python/InstaBot/src/instabot.py", line 485, in log_in
    self.csrf_token = extract_login.cookies['csrftoken']
  File "/Users/XXX/Library/Python/2.7/lib/python/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/XXX/Library/Python/2.7/lib/python/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

Apologies, I could not sign you in.

**Comment by AcidBurn86** [comment]
same problem.. any solution?

**Comment by tahasamar** [comment]
same :(

**Comment by gormlabenz** [comment]
same

**Comment by froz0ned** [comment]
same here :(

**Comment by elemosel** [comment]
Same here
