### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by markeeey** [nickpettican/InstaBot#75]
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Could not open config file, check parameters.')?

any help?

**Comment by markeeey** [comment]
i figured it out, basically you have to replace, print 'Could not open config file, check parameters' with:
print ("Could not open config file, check parameters.")

but i still have another problem: Traceback (most recent call last):
File "C:\Users\User\Desktop\bot\InstaBot-master\run.py", line 23, in <module>
    from src.instabot import InstaBot
File "C:\Users\User\Desktop\bot\InstaBot-master\src\instabot.py", line 623
    print '\n\t--- Delaying %s seconds ---' % (sleep_time)
