### ISSUE TITLE
Time / Hours / All Day

### ISSUE THREAD

**Issue by hoeger** [nickpettican/InstaBot#9]
What is the correct way to get the All-Day operation mode?

**config.json**

```
{
       [...]
        "bot_start_at": "10:00",
        "bot_stop_at": "10:00"
}
```

I get this output:

```
Trying to sign in as [...]...  successfully signed in
Starting operations - 11:02:17 17/06/2017
Traceback (most recent call last):
  File "run.py", line 52, in <module>
    main()
  File "run.py", line 48, in main
    instabot.main()
  File "/home/hoeger/ib-nickpettican/src/instabot.py", line 603, in main
    if self.times['start_bot'] > self.time_now():
AttributeError: InstaBot instance has no attribute 'times'
```

**config.json**

```
        "bot_start_at": "10:00",
        "bot_stop_at": "12:00"
```
Output:

```
Starting operations - 11:03:49 17/06/2017

Current daily count:
 - All operations: 0
 - Like news feed: 0
 - Likes: 0
 - Follows: 0
 - Unfollows: 0
 - Comments: 0

Finishing operations...
```

**config.json**

```
        "bot_start_at": "00:01",
        "bot_stop_at": "23:59"
```
Output:

```
Starting operations - 11:15:03 17/06/2017

Current daily count:
 - All operations: 2199
 - Like news feed: 0
 - Likes: 669
 - Follows: 667
 - Unfollows: 667
 - Comments: 196
```

**Comment by nickpettican** [comment]
Hi @hoeger, thanks for finding this bug.

Seeing as I didn't test the all-day mode as much as the normal mode it is prone to bugs. By the way, the number of follows you've got there is pretty high! Careful you don't get banned.

I will fix the bug so stay tuned for the update

**Comment by hoeger** [comment]
I have to thank you, it's working like a charm now.

Sorry for the long delay. 

_Subsequent interruptions fills **unfollows.csv** with **""**_

**Comment by nickpettican** [comment]
That's great @hoeger , thanks for the feedback.
